site:
  title: Clinical e-portfolio
  start_page: e-portofolio::home.adoc
content:
  sources:
  - url: .
    branches: HEAD
ui:
  bundle:
    url: ./ui-bundle
    snapshot: true
    
asciidoc:
  # Some built-in AsciiDoc attributes are not applicable in the Antora
  # environment. These attributes include data-uri, allow-uri-read, docinfo,
  # linkcss, noheader, nofooter, webfonts, and outfilesuffix.
  attributes:
    # previous and next page navigation, uses nav.adoc
    page-pagination: ''
    idprefix: ''
    stem: latexmath
  extensions:
    - asciidoctor-kroki